# Generated by Django 5.0.4 on 2024-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_address_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='anon@gmail.com', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
