# Generated by Django 5.0.4 on 2024-04-18 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_date_joined_message_wishitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 14, 25, 40, 850000, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
