# Generated by Django 5.0.4 on 2024-04-18 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cartitem_user_alter_user_date_joined_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 15, 20, 45, 187838, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
