# Generated by Django 5.0.4 on 2024-04-19 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_count_in_stock_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_by',
        ),
        migrations.AddField(
            model_name='message',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default='regular sample'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 11, 9, 17, 816086, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.DeleteModel(
            name='SoldItem',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
